version: '3'

services:
  web:
    image: nginx:latest
    container_name: web
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php/index.php:/var/www/html/index.php
      - ./php/index.css:/var/www/html/index.css
    depends_on:
      - php

  php:
    build: ./php
    container_name: php
    volumes: 
      - ./php/index.php:/var/www/html/index.php
    depends_on:
      - db
  
  db:
    image: mariadb:latest
    container_name: db
    volumes:
      - ./mariadb/start.sql:/docker-entrypoint-initdb.d/start.sql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: 8inf876
      MYSQL_USER: php 
      MYSQL_PASSWORD: php_password 